// Run by .github/workflows/update-frame-weather.yml on a schedule (via
// `node frame/generate-weather.js`) to bake a live weather description into
// frame/weather.js as a plain static <script>. This runs ahead of time
// rather than in the browser because the device that captures /frame takes
// its screenshot without waiting for in-page fetch()es to resolve, so a
// client-side weather fetch was rendering as "Loading today's weather...".
const fs = require("fs");
const path = require("path");

const LOCATION = { name: "Berkeley", latitude: 37.8715, longitude: -122.2730 };
const TIME_ZONE = "America/Los_Angeles";

// WMO weather codes, as returned by open-meteo.com's daily forecast.
const WEATHER_CODES = {
    0: "Clear sky", 1: "Mainly clear", 2: "Partly cloudy", 3: "Overcast",
    45: "Foggy", 48: "Foggy with rime frost",
    51: "Light drizzle", 53: "Drizzle", 55: "Heavy drizzle",
    56: "Light freezing drizzle", 57: "Freezing drizzle",
    61: "Light rain", 63: "Rain", 65: "Heavy rain",
    66: "Light freezing rain", 67: "Freezing rain",
    71: "Light snow", 73: "Snow", 75: "Heavy snow", 77: "Snow grains",
    80: "Light rain showers", 81: "Rain showers", 82: "Heavy rain showers",
    85: "Light snow showers", 86: "Heavy snow showers",
    95: "Thunderstorms", 96: "Thunderstorms with hail", 99: "Severe thunderstorms with hail"
};

const COMPASS_DIRECTIONS = [
    "N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE",
    "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"
];

function compassDirection(deg) {
    return COMPASS_DIRECTIONS[Math.round(deg / 22.5) % 16];
}

async function main() {
    const url = "https://api.open-meteo.com/v1/forecast" +
        "?latitude=" + LOCATION.latitude +
        "&longitude=" + LOCATION.longitude +
        "&daily=weathercode,temperature_2m_max,temperature_2m_min,windspeed_10m_max,winddirection_10m_dominant" +
        "&temperature_unit=fahrenheit&windspeed_unit=mph" +
        "&timezone=" + encodeURIComponent(TIME_ZONE) +
        "&forecast_days=1";

    const res = await fetch(url);
    if (!res.ok) {
        throw new Error("open-meteo request failed: " + res.status);
    }
    const json = await res.json();
    const daily = json.daily;

    const code = daily.weathercode[0];
    const high = Math.round(daily.temperature_2m_max[0]);
    const low = Math.round(daily.temperature_2m_min[0]);
    const windSpeed = Math.round(daily.windspeed_10m_max[0]);
    const windDir = compassDirection(daily.winddirection_10m_dominant[0]);
    const description = WEATHER_CODES[code] || "Weather conditions";

    const caption = description + " in " + LOCATION.name +
        " today, with a high near " + high + "°F and a low around " +
        low + "°F overnight. " + windDir + " wind, up to " + windSpeed + " mph.";

    const output = "// Auto-generated by frame/generate-weather.js via a scheduled GitHub\n" +
        "// Actions workflow (.github/workflows/update-frame-weather.yml).\n" +
        "// Do not edit by hand — it's overwritten on the next scheduled run.\n" +
        "window.FRAME_WEATHER = " + JSON.stringify(caption) + ";\n";

    fs.writeFileSync(path.join(__dirname, "weather.js"), output);
    console.log("Wrote frame/weather.js:", caption);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
