// Run by .github/workflows/update-frame-transit.yml on an hourly schedule
// (via `node frame/generate-transit.js`) to bake live AC Transit predictions
// into frame/transit.js as a plain static <script>, appended to the weather
// caption. Same reason as frame/generate-weather.js: the device capturing
// /frame doesn't wait for in-page fetch()es, so this has to run ahead of
// time and commit a static result.
const fs = require("fs");
const path = require("path");

const TIME_ZONE = "America/Los_Angeles";
const WINDOW_MINUTES = 60; // matches the hourly refresh cadence
const API_KEY = process.env.TRANSIT_511_API_KEY;

// Route "72" at stop 55501 is actually three branded sub-lines (72, 72M,
// 72L) that all stop there — matched by the optional trailing letter and
// shown as e.g. "4:17(M)". Route "12" has no such variants, so the plain
// regex just matches "12" exactly.
const STOPS = [
    { stopCode: "51175", route: "12" },
    { stopCode: "55501", route: "72" }
];

// "Gilman St & Curtis St" -> "Gilman & Curtis". No direction word (e.g.
// "southbound") either -- the cross street already tells you which stop,
// and every character here counts against the 4-line footer clamp in
// text-canvas.js.
var STREET_SUFFIX = /\s+(St|Ave|Av|Blvd|Rd|Dr|Way|Pl|Ct|Ln)\.?$/i;
function shortStopName(fullName) {
    return fullName.split(" & ").map(function (part) {
        return part.replace(STREET_SUFFIX, "");
    }).join(" & ");
}

// No AM/PM suffix -- every departure in the WINDOW_MINUTES lookahead falls
// within the same part of the day, so it'd just be repeated noise.
function formatTime12h(date) {
    return date.toLocaleTimeString("en-US", {
        timeZone: TIME_ZONE,
        hour: "numeric",
        minute: "2-digit"
    }).replace(/\s*[AP]M$/i, "");
}

async function fetchStopMonitoring(stopCode) {
    const url = "https://api.511.org/transit/StopMonitoring" +
        "?api_key=" + encodeURIComponent(API_KEY) +
        "&agency=AC&stopcode=" + encodeURIComponent(stopCode) +
        "&format=json";
    // 511.org always gzip-compresses the response regardless of the
    // request's Accept-Encoding; fetch() decompresses transparently.
    const res = await fetch(url);
    if (!res.ok) {
        throw new Error("511.org request failed for stop " + stopCode + ": " + res.status);
    }
    const json = await res.json();
    return json.ServiceDelivery.StopMonitoringDelivery.MonitoredStopVisit || [];
}

function buildStopSegment(stopCode, route, visits, now) {
    const routePattern = new RegExp("^" + route + "([A-Z])?$");
    const windowEnd = new Date(now.getTime() + WINDOW_MINUTES * 60 * 1000);

    const matches = visits.filter(function (visit) {
        return routePattern.test(visit.MonitoredVehicleJourney.LineRef);
    });

    const entries = matches.map(function (visit) {
        const call = visit.MonitoredVehicleJourney.MonitoredCall;
        const variant = visit.MonitoredVehicleJourney.LineRef.match(routePattern)[1] || "";
        const time = new Date(call.ExpectedArrivalTime || call.AimedArrivalTime);
        return {
            time: time,
            label: formatTime12h(time) + (variant ? "(" + variant + ")" : ""),
            stopName: call.StopPointName
        };
    }).filter(function (entry) {
        return entry.time <= windowEnd;
    }).sort(function (a, b) {
        return a.time - b.time;
    });

    if (entries.length === 0) {
        return route + ": no buses in the next hour";
    }

    const stopName = shortStopName(entries[0].stopName);
    const times = entries.map(function (e) { return e.label; }).join(", ");

    return route + " (" + stopName + "): " + times;
}

async function main() {
    if (!API_KEY) {
        throw new Error("TRANSIT_511_API_KEY environment variable is not set");
    }

    const now = new Date();
    const segments = [];
    // Sequential, not parallel: 511.org's default rate limit is 60
    // requests/hour and this is cheap enough not to need the speed.
    for (const stop of STOPS) {
        const visits = await fetchStopMonitoring(stop.stopCode);
        segments.push(buildStopSegment(stop.stopCode, stop.route, visits, now));
    }

    const caption = segments.join("\n");

    const output = "// Auto-generated by frame/generate-transit.js via a scheduled GitHub\n" +
        "// Actions workflow (.github/workflows/update-frame-transit.yml).\n" +
        "// Do not edit by hand — it's overwritten on the next scheduled run.\n" +
        "window.FRAME_TRANSIT = " + JSON.stringify(caption) + ";\n";

    fs.writeFileSync(path.join(__dirname, "transit.js"), output);
    console.log("Wrote frame/transit.js:", caption);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
