// Auto-generated by frame/generate-transit.js via a scheduled GitHub
// Actions workflow (.github/workflows/update-frame.yml). Rendered by
// render.js/text-canvas.js, which filter out already-departed entries
// and fit as many as the box's actual width allows -- see
// renderTransitFooter in text-canvas.js.
// Do not edit by hand — it's overwritten on the next scheduled run.
window.FRAME_TRANSIT = [{"route":"12","stopName":"Gilman & Curtis","entries":[{"time":"2026-09-01T13:10:17.000Z","label":"6:10","live":true},{"time":"2026-09-01T13:10:42.000Z","label":"6:10","live":false},{"time":"2026-09-01T13:30:42.000Z","label":"6:30","live":false}]},{"route":"72","stopName":"San Pablo & Gilman","entries":[{"time":"2026-09-01T12:40:14.000Z","label":"5:40(M)","live":true},{"time":"2026-09-01T12:54:55.000Z","label":"5:54","live":true},{"time":"2026-09-01T12:55:09.000Z","label":"5:55","live":false},{"time":"2026-09-01T13:10:09.000Z","label":"6:10(M)","live":false},{"time":"2026-09-01T13:25:09.000Z","label":"6:25","live":false},{"time":"2026-09-01T13:39:27.000Z","label":"6:39(M)","live":false}]}];
