// Auto-generated by frame/generate-transit.js via a scheduled GitHub
// Actions workflow (.github/workflows/update-frame.yml).
// Do not edit by hand — it's overwritten on the next scheduled run.
window.FRAME_TRANSIT = "12 (Gilman & Curtis): 6:56, 7:23, 7:51\n72 (San Pablo & Gilman): 7:02, 7:02(L), 7:12(M), 7:21(L), 7:26, 7:40(M)";
