// Auto-generated by frame/generate-transit.js via a scheduled GitHub
// Actions workflow (.github/workflows/update-frame.yml). Rendered by
// render.js/text-canvas.js, which filter out already-departed entries
// and fit as many as the box's actual width allows -- see
// renderTransitFooter in text-canvas.js.
// Do not edit by hand — it's overwritten on the next scheduled run.
window.FRAME_TRANSIT = [{"route":"12","stopName":"Gilman & Curtis","entries":[{"time":"2026-09-01T01:54:07.000Z","label":"6:54","live":true},{"time":"2026-09-01T02:24:13.000Z","label":"7:24","live":true},{"time":"2026-09-01T02:51:16.000Z","label":"7:51","live":false}]},{"route":"72","stopName":"San Pablo & Gilman","entries":[{"time":"2026-09-01T01:54:56.000Z","label":"6:54(L)","live":true},{"time":"2026-09-01T01:59:45.000Z","label":"6:59","live":true},{"time":"2026-09-01T02:11:40.000Z","label":"7:11(M)","live":true},{"time":"2026-09-01T02:22:16.000Z","label":"7:22(L)","live":true},{"time":"2026-09-01T02:25:17.000Z","label":"7:25","live":true},{"time":"2026-09-01T02:41:40.000Z","label":"7:41(M)","live":true},{"time":"2026-09-01T02:42:44.000Z","label":"7:42(M)","live":false},{"time":"2026-09-01T02:54:42.000Z","label":"7:54(L)","live":false},{"time":"2026-09-01T02:57:44.000Z","label":"7:57","live":false},{"time":"2026-09-01T03:12:44.000Z","label":"8:12(M)","live":false}]}];
