// Auto-generated by frame/generate-weather.js via a scheduled GitHub
// Actions workflow (.github/workflows/update-frame.yml).
// Do not edit by hand — it's overwritten on the next scheduled run.
window.FRAME_WEATHER = {"temp":63,"high":68,"low":57,"icon":"cloudy","sunGlyph":"↓","sunTime":"7:38p","ariaLabel":"63°F, with a high near 68°F and a low around 57°F overnight. Overcast expected. Sunset at 7:38 PM."};
