// Auto-generated by frame/generate-weather.js via a scheduled GitHub
// Actions workflow (.github/workflows/update-frame-weather.yml).
// Do not edit by hand — it's overwritten on the next scheduled run.
window.FRAME_WEATHER = {"temp":71,"high":75,"low":56,"icon":"fog","sunGlyph":"↓","sunTime":"7:47p","ariaLabel":"71°F, with a high near 75°F and a low around 56°F overnight. Foggy expected. Sunset at 7:47 PM."};
