// Auto-generated by frame/generate-weather.js via a scheduled GitHub
// Actions workflow (.github/workflows/update-frame-weather.yml).
// Do not edit by hand — it's overwritten on the next scheduled run.
window.FRAME_WEATHER = "69°F, with a high near 69°F and a low around 57°F overnight. Sunset at 7:48 PM. Light drizzle expected.";
